version: '3.7'

services:
  cards-db:
    image: card-db:latest
    build:
      context: ./cards-db
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    # environment:
    #   ACCEPT_EULA: "Y"
    #   SA_PASSWORD: "Pass"
    # networks:
    #   - backend

networks:
  backend:
    name: backend
    driver: bridge
    attachable: true
    external: false
